apiVersion: v1
kind: Service
metadata:
  name: {{ include "controller.name" . }}
  labels:
    {{- include "controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.controller.service.type }}
  ports:
    {{- toYaml .Values.controller.ports | nindent 4 }}
  selector:
    {{- include "controller.selectorLabels" . | nindent 4 }}
