apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: global
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    higress: {{ .Release.Namespace }}-{{ include "gateway.name" . }}
  servers:
    - hosts:
        - "*"
      port:
        name: http-80
        number: 80
        protocol: HTTP

---
